### ISSUE TITLE
Request: add extended clades to references

### ISSUE THREAD

**Issue by tantrev** [LiuzLab/SalmonTE#21]
Hello!  I was looking through SalmonTE's references and noticed that their clades don't seem to have all of those listed in the "clades_extended.csv" file.  It would just be really nice if all of the clades could be included in all of the references. :)

**Comment by hyunhwaj** [comment]
Hello @tantrev,

I am traveling, so I could not reach you promptly. Could you inform which clades I am missing?

Thank you,

Hyun-Hwan Jeong

**Comment by tantrev** [comment]
Hello!  So sorry for the delay.  The clades I'm most interested in are the DNA transposons - it would just be really nice if they could be in the reference for all species (similar to TEtranscripts).
