### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by vasilislenis** [LiuzLab/SalmonTE#25]
Hello and a happy new year!

I have installed SalmonTE and seems everything went well. However, when I tried to run the example in order to test it, I am receiving the following error:

`2019-01-07 14:29:47,305 Starting quantification mode`
`2019-01-07 14:29:47,305 Collecting FASTQ files...`
`2019-01-07 14:29:47,306 The input dataset is considered as a single-end dataset.`
`2019-01-07 14:29:47,306 The input dataset is considered as a single-end dataset.`
`Traceback (most recent call last):`
 ` File "/home/x.v.l.01/SalmonTE/SalmonTE.py", line 285, in <module>`
   ` run(args)`
 ` File "/home/x.v.l.01/SalmonTE/SalmonTE.py", line 231, in run`
    `param = {**args, **collect_FASTQ_files(args['FILE'])}`
 ` File "/home/x.v.l.01/SalmonTE/SalmonTE.py", line 125, in collect_FASTQ_files`
    `os.symlink(os.path.abspath(file), file_name)`
`FileExistsError: [Errno 17] File exists: '/lustrehome/home/x.v.l.01/SalmonTE/example/CTRL_2_R1.fastq'` `-> '/tmp/tmp0vsal2pn/x.fastq'`

It looks like it has an issue in parsing the fastq files.
Any help with this would be much appreciated.

Kind regards,
Vasilis.

**Comment by hyunhwaj** [comment]
@vasilislenis,

This looks like the error is because of the file `/tmp/tmp0vsal2pn/x.fastq` exists in your machine, so can you purge `/tmp/tmp0vsal2pn/` and execute SalmonTE again? Can you also tell me what exact command line you used and which OS you are using?

Thank you,

Hyun-Hwan Jeong

**Comment by vasilislenis** [comment]
Hi Hyun,

Thank you very much for answering me.

I have purge the /tmp/tmp0vsal2pn/ folder but the error still remains.

I am running it on an HPC cluster (linux OS) with R/3.5.1, python/3.7.0 and anaconda/3

The command that I am trying is for the testing example:

SalmonTE.py quant --reference=hs example

Many thanks,
Vasilis.

**Comment by hyunhwaj** [comment]
@vasilislenis Can you pull this github repository and run the command again? I did a minor change and believe it works with you.

Best Regards,

Hyun-Hwan Jeong
