### ISSUE TITLE
SnakeFile Single Issue

### ISSUE THREAD

**Issue by juanb001** [LiuzLab/SalmonTE#26]
Hi,

I'm having an issue with single-end data on the latest version of SalmonTE and latest version of snakemake.

<img width="1288" alt="screen shot 2019-02-06 at 1 02 41 am" src="https://user-images.githubusercontent.com/47381639/52330709-f00be000-29aa-11e9-9b24-c0fa3baa6014.png">

**Comment by hyunhwaj** [comment]
@juanb001 

Can you show me the list of the file names in the trimmed directory?

Thank you,

Hyun-Hwan Jeong

**Comment by juanb001** [comment]
Here it is!

<img width="885" alt="screen shot 2019-02-06 at 2 55 23 pm" src="https://user-images.githubusercontent.com/47381639/52379420-4dda0f80-2a1f-11e9-8788-045f70d82b7c.png">

**Comment by hyunhwaj** [comment]
@juanb001 Thanks for reporting this. This error was because a rule had been omitted in the Snakefile. I have fixed and committed it - 600fe2e300e11dad90d5051a65a6813d6afea748. Can you pull the github repository run this again? 

Thank you,

Hyun-Hwan Jeong

**Comment by juanb001** [comment]
I re-downloaded and re-run, but now I'm getting this error:

<img width="1273" alt="screen shot 2019-02-06 at 5 06 04 pm" src="https://user-images.githubusercontent.com/47381639/52384262-8c78c580-2a31-11e9-8547-0a0597e477b3.png">

**Comment by juanb001** [comment]
When I change directory to where my FASTQ files are (the /trimmed folder) and run SalmonTE from there, I believe it is working. However, the above issue happened when the current directory was the Desktop and I linked to the /Desktop/Senescence_Fibro_trimmed folder when I ran the program.

**Comment by hyunhwaj** [comment]
Can you try it in the same directory with a different output directory (change sen_quant to another)?

Thank you,

Hyun-Hwan Jeong

**Comment by juanb001** [comment]
By same directory, do you mean run it again from the Desktop (like in the error box) but change sen_quant to sen_quantifications (for example)?

**Comment by hyunhwaj** [comment]
Exactly!

**Comment by juanb001** [comment]
The last run (from the folder with the FASTQ files ran successfully).

However, now that I change directory to Desktop I get "Failed to read /Users/juanb/Desktop/Senescence_Fibro/trimmed/". Running from the FASTQ folder gives the same error.

**Comment by juanb001** [comment]
It's working now. The problem I think was, I had the folder from the successful run in the FASTQ folder. SalmonTE had issues with that when it was reading the FASTQ files, I think.

**Comment by hyunhwaj** [comment]
@juanb001 glad to hear that, but I want to figure out a couple of things. 

* What does the successful run mean? Do you mean a run has been completed without any error or a run is/was running? 
* Can you see `.snakemake` (a hidden directory) where you run a command? If you can see, then can you remove/move the folder to other and run the problematic command again?  
* Can you move `sen_quant` folder to another place? I presume that this is because of any process is touching the directory, so `snakemake` can't run.

Thank you,

Hyun-Hwan Jeong

**Comment by hyunhwaj** [comment]
@juanb001 > However, now that I change directory to Desktop I get "Failed to read /Users/juanb/Desktop/Senescence_Fibro/trimmed/". Running from the FASTQ folder gives the same error.

If it is possible then can you make a screenshot or do a copy-and-paste the text message here?

**Comment by juanb001** [comment]
The second error is:

<img width="771" alt="screen shot 2019-02-06 at 6 22 59 pm" src="https://user-images.githubusercontent.com/47381639/52386771-407f4e00-2a3c-11e9-9660-2224fc8b88e5.png">

Which seems to be caused by the extra files that aren't FASTQ in the same directory as FASTQ files. If I delete sen_quant_complete, SalmonTE runs successfully, otherwise it does not:

<img width="851" alt="screen shot 2019-02-06 at 6 26 23 pm" src="https://user-images.githubusercontent.com/47381639/52386885-bedbf000-2a3c-11e9-9887-237204744868.png">


By successful run, I mean I was able to complete the quantification step.
<img width="771" alt="screen shot 2019-02-06 at 6 22 59 pm" src="https://user-images.githubusercontent.com/47381639/52386792-5260f100-2a3c-11e9-8841-461bdb8db94e.png">

I don't see .snakemake. I can't move sen_quant since it doesn't seem to exist. There's no folder on my Desktop with that name; terminal doesn't show it either with the ls command. If I change sen_quant -> sen_quantif the quantification goes to completion. 

Finally, when I do the test function, to compare sample A to sample B I get this error. Is it because I only have one replicate for each? Are single replicates no longer supported?
<img width="862" alt="screen shot 2019-02-06 at 6 35 20 pm" src="https://user-images.githubusercontent.com/47381639/52387171-fc8d4880-2a3d-11e9-9522-4c26e1a078bc.png">

**Comment by hyunhwaj** [comment]
SalmonTE uses DESeq2, and the latest version of DESeq2 no longer supports single replicates. One possible solution is downgrading the version of DESeq2, and you can do it with the following command line in R:

```r
 install.packages("https://bioconductor.org/packages/3.6/bioc/src/contrib/Archive/DESeq2/DESeq2_1.18.0.tar.gz", repos=NULL)
```

**Comment by hyunhwaj** [comment]
@juanb001 

> I don't see .snakemake. I can't move sen_quant since it doesn't seem to exist. There's no folder on my Desktop with that name; terminal doesn't show it either with the ls command. If I change sen_quant -> sen_quantif the quantification goes to completion.

You even did not see the folder when you use `ls -alh`?

**Comment by hyunhwaj** [comment]
@juanb001 Does the DESeq2 solution help you?

**Comment by juanb001** [comment]
Thanks for the help! I tried to run the code you provided but it sadly gives an error, so I can't run single replicates for now., but this is a limitation with R. 

<img width="928" alt="screen shot 2019-02-07 at 12 27 30 pm" src="https://user-images.githubusercontent.com/47381639/52440731-c8646700-2ad3-11e9-8dcf-3b61b47a301c.png">

**Comment by hyunhwaj** [comment]
@juanb001 Have you installed homebrew in your machine? If then, `brew install gfortran` and run the code will help you.

**Comment by juanb001** [comment]
I believe it's already installed, but I still got the error (on a Mac at work). I repeated the test on my computer running linux and did the single replicate comparison without any issues. Based on others' comments it seems I need to change the version of R on the mac. I'll figure it out. In any case, thanks for the help!
