### ISSUE TITLE
mapping strategy

### ISSUE THREAD

**Issue by AlicePsyche** [LiuzLab/SalmonTE#29]
Hi,

Thanks for your great tool ~

I have read the website and your recent published  PSB paper but still could not understand the mapping strategy for repeats (Sorry I am not familiar with bioinformatics). I have some simple questions:
1. How does SalmonTE deal with multiple mapping reads? or only use unique mapping reads for count.
2. How does SalmonTE deal with the  multi-overlapping reads ( a read which covers different gene)?
3. Is it possible to detect the differential expressed TE if I only had one replicate? 

Is there any documentation I could refer to? 

Thanks for your help in advance. Sorry for my naive questions...

Best,
Alice

**Comment by hyunhwaj** [comment]
> Hi,
> 
> Thanks for your great tool ~
>
Thanks for your interests, @AlicePsyche!
 
> I have read the website and your recent published PSB paper but still could not understand the mapping strategy for repeats (Sorry I am not familiar with bioinformatics). I have some simple questions:
> 
> 1. How does SalmonTE deal with multiple mapping reads? or only use unique mapping reads for count.

SalmonTE uses Salmon as a core algorithm of the quantification, and the algorithm includes stochastic models such as SCVB0 or EM to get rid of the read ambiguity. Thus, SalmonTE will consider all reads for the TE quantification.

> 2. How does SalmonTE deal with the  multi-overlapping reads ( a read which covers different gene)?

I think you are asking what if a read can belong to a gene or a TE. Is it correct? Based on my observation TE sequence are not placed to parts will be transcribed, so I believe there is no issue with that if you consider transcriptome. 

> 3. Is it possible to detect the differential expressed TE if I only had one replicate?

As I mentioned in #26, the latest DESeq2 no longer allows test with one replicate, and a possible solution would be using an old version of the DESeq2. Please read the thread in the issue.

> 
> Is there any documentation I could refer to?
> 
I believe the original Salmon paper is the documentation what you need to read: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5600148/

> Thanks for your help in advance. Sorry for my naive questions...
> 
> Best,
> Alice

**Comment by AlicePsyche** [comment]
Thanks for your detail explanation. I would read the Salmon paper. Thanks ;)
