### ISSUE TITLE
No version or release tagged

### ISSUE THREAD

**Issue by ebirn** [LiuzLab/SalmonTE#30]
README file mentions version 0.4 however this is not tagged in the repository.

> December 19, 2018: SalmonTE has been updated to 0.4 with some improvements!

Please tag/release your versions here on Github too, so that we can provide reproducible software installations for our scientists.
Today's clone of master branch is not necessarily the same as yesterdays.

Best,
Erich

**Comment by hyunhwaj** [comment]
Thanks for the suggestion, and now I have added a tag for the v0.4 https://github.com/LiuzLab/SalmonTE/releases/tag/v0.4

Best,

Hyun-Hwan Jeong
