### ISSUE TITLE
Creation of index with fasta

### ISSUE THREAD

**Issue by fripeki** [LiuzLab/SalmonTE#35]
Hello, Yesterday I 've installed successfully salmonTE but I need to create a new index because I have a library of transposable elements of my species. The problem is that I cannot create the index because the names of the classes and species of elements in the fasta file don't satisfy the requisites. The library is manually curated. How can solve this problem?

**Comment by fripeki** [comment]
HI, sorry again, could I send you the fasta file, so you can tell me if is it usable for the analysis, ora suggest me how to modify it? I don't have idea how can make it usable. I'm waiting for your help. Thank you again and congrats

**Comment by hyunhwaj** [comment]
@fripeki, Yes please send your fasta file with telling me what type of species you are using.

Thank you,

Hyun-Hwan Jeong

**Comment by fripeki** [comment]
I've send you the mail. Thank you
Regards

**Comment by BenjaminSchwessinger** [comment]
Hi,
I have a related question. Is there a tutorial or some information of how to generate once own reference from non-model organism TEs. We should be able to get this coded out if there were some information of how references are build and what formats are needed. Thanks!
