### ISSUE TITLE
run_salmon_fq and EXPR.csv file not found error

### ISSUE THREAD

**Issue by shreya1704** [LiuzLab/SalmonTE#37]
I am using SalmonTE 0.4 with default quant function and getting following error.

<img width="2559" alt="Screen Shot 2019-08-12 at 5 18 30 PM" src="https://user-images.githubusercontent.com/33744933/62899476-d8306280-bd25-11e9-9ee6-e1b3296e37b2.png">

**Comment by hyunhwaj** [comment]
Hello @shreya1704,

* What was the command-line you used when you saw the error?
* What can you see if you run `/Users/chenlab/SalmonTE/salmon/darwin/bin/salmon`?

Thank you,

Hyun-Hwan Jeong

**Comment by shreya1704** [comment]
Hi Hyun-Hwan,

1. I was just running SalmonTE.py quant --reference=hs example when I got the error.

2. 
<img width="555" alt="Screen Shot 2019-08-13 at 10 27 58 AM" src="https://user-images.githubusercontent.com/33744933/62950010-48d29000-bdb5-11e9-9594-980fab3281fc.png">

Thanks.

**Comment by hyunhwaj** [comment]
Please follow the instruction below (this is from `README.md`);

**Q. I am using `SalmonTE` on `macOS` and `salmonTE` fails to run on `quant` mode with error messages:**

```
CalledProcessError in line xx of SOME_PATH:
Command ' set -euo pipefail;  ROOT_OF_SALMON_TE/SalmonTE/salmon/darwin/bin/salmon quant...' returned non-zero exit status 134.
```

**A.** You may have a problem to run `salmon` which is an essential tool for the pipeline. You may install [Threading Building Blocks library](https://www.threadingbuildingblocks.org/download) to solve the problem. If you are using [homebrew](https://brew.sh) then please use below command:

```
brew install tbb
```

Best,

Hyun-Hwan Jeong

**Comment by shreya1704** [comment]
It is working now. Thank you
