### ISSUE TITLE
condition problems

### ISSUE THREAD

**Issue by nrius** [LiuzLab/SalmonTE#39]
Hi!
quant created a condition.csv file, but since in the README says that it should be called control.csv I made the modifications and copied condition.csv into control.csv.  I get this error, and I think it's telling me there is something wrong with the condition.csv file. 

```
Step 1: Loading required libraries...
Step 2: Loading input data...
Step 3: Running the DE analysis...
Error in `$<-.data.frame`(`*tmp*`, "condition", value = integer(0)) : 
  replacement has 0 rows, data has 28
Calls: SalmonTE -> $<- -> $<-.data.frame
Execution halted
```
Both control.csv and condition.csv look like this:

```
SRR1111111_S1_L001_R2_001,condition
SRR2111111_S1_L001_R2_001,condition
SRR3111111_S1_L001_R2_001,control
SRR4111111_S1_L001_R2_001,control
SRR5111111_S1_L001_R2_001,control
SRR6111111_S1_L001_R2_001,condition
(...)
SRR2811111_S1_L001_R2_001,condition
```
Also, in the command line I specified `--conditions=control,condition` without whitespaces.

Do you have an idea for what is going wrong here?

Thank you

**Comment by hyunhwaj** [comment]
Hi @nrius, there was an error on README.md (`control.csv` should be replaced as `condition.csv`, sorry for the confusion), and I have corrected it. Did you include `SampleID,control` to the first line of the file? It might not work if you didn't include the line in the file. And again, all the sample information has to be inside of `condition.csv'.  If it does not solve your problem then, please send your EXPR.csv file. 

Thank you,

Hyun-Hwan Jeong

**Comment by nrius** [comment]
Hi,
The condition.csv file was ok, but it turns out the names of the fastqs were too long, I shortened them to 10 characters with only one underscore and it worked perfectly.

Thanks for your reply,

Nuria

**Comment by hyunhwaj** [comment]
@nrius, I believe this was not supposed to happen, so can you share the name of files, EXPR.csv, and condition.csv to hyunhwaj@bcm.edu if you don't mind? It should be helpful to improve this tool.

Thank you,

Hyun-Hwan Jeong

**Comment by nrius** [comment]
Hi Hyun-Hwan Jeong
Sure, in the attachment, you can find the initial EXPR and condition files
(before the change name).
Hope it helps.

Best,

Nuria





Nuria Rius Camps
