### ISSUE TITLE
fasta files as input

### ISSUE THREAD

**Issue by savytskanatalia** [LiuzLab/SalmonTE#40]
Thank you very much for your tool!
I had a question, if SalmonTE can take fasta files with raw reads as input, instead of fastq?
I am currently working on simulated data, and output of the simulator is always .fasta. Salmon itself seems to be taking .fa as raw input for quasimapping, but trying to run SalmonTE with my files results in error for collect_mappability. So I was wondering, if the error I get is due to the input file format or may be connected to something else.
Thank you for reply in advance.

The command I use is following:
`SalmonTE.py quant --reference=mm --outpath=salmonte --num_threads=20 --exprtype=count simulated/sample_01_1.fasta.gz simulated/sample_01_2.fasta.gz`

The error details I get are in the screenshot.
![image](https://user-images.githubusercontent.com/43849297/71256847-5a631000-2332-11ea-8caf-94e80b79d8e2.png)

**Comment by hyunhwaj** [comment]
Dear @savytskanatalia,

We don't plan to support FASTA files. But I believe this will help you: http://seqanswers.com/forums/showthread.php?t=58790

Best Regards,

Hyun-Hwan Jeong

**Comment by savytskanatalia** [comment]
> Dear @savytskanatalia,
> 
> We don't plan to support FASTA files. But I believe this will help you: http://seqanswers.com/forums/showthread.php?t=58790
> 
> Best Regards,
> 
> Hyun-Hwan Jeong

Thank you for your reply!
