### ISSUE TITLE
Test example failed

### ISSUE THREAD

**Issue by olferievm** [LiuzLab/SalmonTE#49]
Deployed SalmonTE on OSX Cathalina as follows.
~~~
% R --version
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
% python -V
Python 3.8.2
% pip install --upgrade pip
% pip install docopt
% pip install snakemake

% cd NGSToools
% git clone https://github.com/hyunhwaj/SalmonTE
% echo -n 'export PATH=$HOME/NGSToools/Salmon:$PATH' >> ~/.zshrc
% source ~/.zshrc
~~~

Try to run the test script and got an error.
~~~
% cd Salmon
% SalmonTE.py test --inpath=SalmonTE_output --outpath=SalmonTE_statistical_test --tabletype=csv --figtype=png --analysis_type=DE --conditions=control,treatment
2020-11-20 20:13:41,631 Input path is specified incorrectly!
~~~

Try to run quantification and have the other error.
~~~
% SalmonTE.py quant --reference=hs example
2020-11-20 20:15:17,489 Starting quantification mode
2020-11-20 20:15:17,489 Collecting FASTQ files...
2020-11-20 20:15:17,489 SalmonTE assumes that 'example' is a directory, and SalmonTE will search any FASTQ file in the directory.
2020-11-20 20:15:17,496 The input dataset is considered as a paired-ends dataset.
2020-11-20 20:15:17,497 Collected 4 FASTQ files.
2020-11-20 20:15:17,497 Quantification has been finished.
2020-11-20 20:15:17,497 Running Salmon using Snakemake
/var/folders/fh/6cn8tw8s2ns8shxj_m1gdy400000gn/T/tmpqb8nxbk9
/Users/olferievm/NGSTools/SalmonTE/SalmonTE_output/
/Users/olferievm/NGSTools/SalmonTE/reference/hs
/Users/olferievm/NGSTools/SalmonTE/snakemake/Snakefile.paired:103: SyntaxWarning: "is" with a literal. Did you mean "=="?
Job counts:
	count	jobs
	1	all
	1	collect_abundance
	1	collect_mappability
	3
2020-11-20 20:15:17,786 Job counts:
	count	jobs
	1	all
	1	collect_abundance
	1	collect_mappability
	3
/Users/olferievm/NGSTools/SalmonTE/snakemake/Snakefile.paired:103: SyntaxWarning: "is" with a literal. Did you mean "=="?
Job counts:
	count	jobs
	1	collect_abundance
	1
WorkflowError:
Failed to solve the job scheduling problem with pulp. Please report a bug and use --scheduler greedy as a workaround:
Pulp: cannot execute cbc cwd: /Users/olferievm/NGSTools/SalmonTE
Exiting because a job execution failed. Look above for error message
2020-11-20 20:15:18,147 Exiting because a job execution failed. Look above for error message
Traceback (most recent call last):
  File "/Users/olferievm/NGSTools/SalmonTE/SalmonTE.py", line 296, in <module>
    run(args)
  File "/Users/olferievm/NGSTools/SalmonTE/SalmonTE.py", line 247, in run
    run_salmon(param)
  File "/Users/olferievm/NGSTools/SalmonTE/SalmonTE.py", line 160, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/olferievm/NGSTools/SalmonTE/SalmonTE_output/EXPR.csv'

~~~

It seems something wrong with the snakemake. Not sure how can I fix it?

Sincerely,

Mike.

**Comment by olferievm** [comment]
Try to do the same on my Ubuntu machine and have the same issue. What is wrong?

**Comment by hyunhwaj** [comment]
Hi @olferievm,

Thanks for reporting this issue, and please understand I may slowly respond to the problem because I have limited time to maintain this software since I have moved to another job. It seems SalmonTE doesn't fit the latest version of `snakemake`. I am going to investigate how to run SalmonTE with the latest `snakemake`. Meanwhile, I would recommend you use `snakemake` version 5.5.0. You can forcefully install the version using this command `pip install snakemake==5.5.0 --force` Let me know if your problem is persistent after you downgrade the `snakemake` version.

Thank you,

Hyun-Hwan Jeong

**Comment by olferievm** [comment]
Hyun-Hwan,

Thank you for your fast reply. Much better. The quantification mode seems to work using snakemake==5.5.0. Still got the problem related to DESeq2 package at the end.

SalmonTE.py quant --reference=hs example
2020-11-23 00:05:23,359 Starting quantification mode
2020-11-23 00:05:23,359 Collecting FASTQ files...
2020-11-23 00:05:23,359 SalmonTE assumes that 'example' is a directory, and SalmonTE will search any FASTQ file in the directory.
2020-11-23 00:05:23,364 The input dataset is considered as a paired-ends dataset.
2020-11-23 00:05:23,364 Collected 4 FASTQ files.
2020-11-23 00:05:23,364 Quantification has been finished.
2020-11-23 00:05:23,364 Running Salmon using Snakemake
/Users/olferievm/NGSTools/SalmonTE/snakemake/Snakefile.paired:103: SyntaxWarning: "is" with a literal. Did you mean "=="?
Job counts:
	count	jobs
	1	all
	1	collect_abundance
	1	collect_mappability
	4	run_salmon_fq
	7
2020-11-23 00:05:23,485 Job counts:
	count	jobs
	1	all
	1	collect_abundance
	1	collect_mappability
	4	run_salmon_fq
	7
/Users/olferievm/NGSTools/SalmonTE/snakemake/Snakefile.paired:103: SyntaxWarning: "is" with a literal. Did you mean "=="?
Job counts:
	count	jobs
	1	collect_abundance
	1
/Users/olferievm/NGSTools/SalmonTE/snakemake/Snakefile.paired:103: SyntaxWarning: "is" with a literal. Did you mean "=="?
Job counts:
	count	jobs
	1	collect_mappability
	1
olferievm@Mikhails-MacBook-Pro SalmonTE % SalmonTE.py test --inpath=SalmonTE_output --outpath=SalmonTE_statistical_test --tabletype=csv --figtype=png --analysis_type=DE --conditions=control,treatment
Step 1: Loading required libraries...
Step 2: Loading input data...
Step 3: Running the DE analysis...
converting counts to integer mode
Error in DESeqDataSet(se, design = design, ignoreRank) :
  variables in design formula cannot contain NA: condition
Calls: SalmonTE ... do.deseq2 -> DESeqDataSetFromMatrix -> DESeqDataSet
Execution halted

**Comment by hyunhwaj** [comment]
I believe this could be resolved by changing `condition.csv` file by following the instruction in `README.md`. Please read this - https://github.com/LiuzLab/SalmonTE#running-test-mode-to-perform-statistical-test

Hyun-Hwan Jeong

**Comment by olferievm** [comment]
Got it. Thank you for your help!
