### ISSUE TITLE
to build indices

### ISSUE THREAD

**Issue by amitpande74** [LiuzLab/SalmonTE#53]
HI,
Can you kindly explain this command 
`SalmonTE.py index [--ref_name=ref_name] (--input_fasta=fa_file) [--te_only]`
I know that the input fasta should be the hg19 but for --te_only which format should be used ? GTF or the BED.

regards.

**Comment by hyunhwan-jeong** [comment]
@amitpande74,

First, I think this question is related #50, and I have attached my answer:

> Dear Yong,
> 
> SalmonTE doesn't requires any GTF file to build an index, and it only requires fasta file. I am not sure how you tried to build your index. If you want to have a support from me, you probably need to share details of your data.
> 
> Thank you,
> 
> Hyun-Hwan Jeong

Second, SalmonTE is not relevant with any version of genome index, it is mainly on TE sequences in RepBase. I recommend you to read our wiki page - https://github.com/LiuzLab/SalmonTE/wiki/How-to-build-a-customized-index to understand `--te_only` option.

Best,

Hyun-Hwan Jeong
